#!/usr/bin/env python3
"""Generate test traceability matrix from YAML catalogs and test COVERS declarations.

Reads runtime_components.yaml and sdk_touchpoints.yaml, scans test files for
COVERS = [...] declarations, and produces:
  - docs/testing/TEST_TRACEABILITY.md  (markdown table)
  - docs/testing/TEST_TRACEABILITY.json (machine-readable)

Usage:
    python scripts/testing/generate_traceability.py
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit(
        "PyYAML is required: pip install pyyaml"
    )

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs" / "testing"
TESTS_DIRS = [
    REPO_ROOT / "tests" / "contracts",
    REPO_ROOT / "tests" / "integration",
    REPO_ROOT / "tests" / "evals",
    REPO_ROOT / "tests" / "drift",
]

# Regex to match COVERS = [...] declarations in Python test files
# Handles multi-line lists and both single and double quotes
COVERS_PATTERN = re.compile(
    r'^COVERS\s*=\s*\[([^\]]*)\]',
    re.MULTILINE | re.DOTALL,
)


def load_catalog(path: Path) -> list[dict]:
    """Load a YAML catalog and return the list of entries."""
    with open(path) as f:
        data = yaml.safe_load(f)
    if data is None:
        return []
    # runtime_components.yaml uses 'components', sdk_touchpoints.yaml uses 'touchpoints'
    return data.get("components", data.get("touchpoints", []))


def scan_test_files() -> dict[str, list[str]]:
    """Scan test directories for COVERS declarations.

    Returns a mapping: component_id -> [test_file_relative_paths].
    """
    coverage_map: dict[str, list[str]] = {}

    for tests_dir in TESTS_DIRS:
        if not tests_dir.is_dir():
            continue
        for py_file in sorted(tests_dir.rglob("*.py")):
            try:
                content = py_file.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue

            match = COVERS_PATTERN.search(content)
            if not match:
                continue

            # Parse the list contents
            raw = match.group(1)
            # Extract quoted strings
            ids = re.findall(r'["\']([^"\']+)["\']', raw)
            rel_path = str(py_file.relative_to(REPO_ROOT))
            for component_id in ids:
                coverage_map.setdefault(component_id, []).append(rel_path)

    return coverage_map


def build_matrix(
    components: list[dict],
    touchpoints: list[dict],
    coverage_map: dict[str, list[str]],
) -> list[dict]:
    """Build the traceability matrix rows."""
    rows = []
    for entry in components:
        cid = entry.get("id", "")
        rows.append({
            "component_id": cid,
            "kind": entry.get("kind", ""),
            "criticality": entry.get("criticality", ""),
            "required_coverage": entry.get("required_coverage", []),
            "covered_by": coverage_map.get(cid, []),
            "status": "covered" if coverage_map.get(cid) else "uncovered",
        })
    for entry in touchpoints:
        cid = entry.get("id", "")
        rows.append({
            "component_id": cid,
            "kind": "sdk_touchpoint",
            "criticality": entry.get("criticality", ""),
            "required_coverage": entry.get("required_coverage", []),
            "covered_by": coverage_map.get(cid, []),
            "status": "covered" if coverage_map.get(cid) else "uncovered",
        })
    return rows


def write_markdown(rows: list[dict], output_path: Path) -> None:
    """Write the traceability matrix as a markdown table."""
    lines = [
        "# Test Traceability Matrix",
        "",
        "Auto-generated by `scripts/testing/generate_traceability.py`.",
        "",
        "| Component ID | Kind | Criticality | Required Coverage | Covered By |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        cov = ", ".join(row["required_coverage"]) if row["required_coverage"] else "-"
        covered = ", ".join(f"`{f}`" for f in row["covered_by"]) if row["covered_by"] else "**UNCOVERED**"
        lines.append(
            f"| `{row['component_id']}` | {row['kind']} | {row['criticality']} | {cov} | {covered} |"
        )

    # Summary
    total = len(rows)
    covered = sum(1 for r in rows if r["status"] == "covered")
    uncovered = total - covered
    critical_uncovered = sum(
        1 for r in rows
        if r["status"] == "uncovered" and r["criticality"] == "critical"
    )
    lines.extend([
        "",
        "## Summary",
        "",
        f"- **Total components:** {total}",
        f"- **Covered:** {covered}",
        f"- **Uncovered:** {uncovered}",
        f"- **Critical uncovered:** {critical_uncovered}",
    ])

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_json(rows: list[dict], output_path: Path) -> None:
    """Write the traceability matrix as JSON."""
    output = {
        "version": 1,
        "matrix": rows,
        "summary": {
            "total": len(rows),
            "covered": sum(1 for r in rows if r["status"] == "covered"),
            "uncovered": sum(1 for r in rows if r["status"] == "uncovered"),
        },
    }
    output_path.write_text(
        json.dumps(output, indent=2) + "\n", encoding="utf-8"
    )


def main() -> None:
    """Entry point."""
    components_path = DOCS_DIR / "runtime_components.yaml"
    touchpoints_path = DOCS_DIR / "sdk_touchpoints.yaml"

    if not components_path.is_file():
        raise SystemExit(f"Missing catalog: {components_path}")
    if not touchpoints_path.is_file():
        raise SystemExit(f"Missing catalog: {touchpoints_path}")

    components = load_catalog(components_path)
    touchpoints = load_catalog(touchpoints_path)
    coverage_map = scan_test_files()
    rows = build_matrix(components, touchpoints, coverage_map)

    md_path = DOCS_DIR / "TEST_TRACEABILITY.md"
    json_path = DOCS_DIR / "TEST_TRACEABILITY.json"

    write_markdown(rows, md_path)
    write_json(rows, json_path)

    covered = sum(1 for r in rows if r["status"] == "covered")
    total = len(rows)
    print(f"Traceability matrix generated: {covered}/{total} components covered")
    print(f"  Markdown: {md_path.relative_to(REPO_ROOT)}")
    print(f"  JSON:     {json_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
